name: unit testing

on:
  push:
  pull_request:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4  # Check out the repository

      - name: get CMake
        run:
          git submodule update --init
          cmake -S . -B build
          cmake --build build -j

      - name: Run Unit Tests  # Run unit tests using Maven
        run: ./build/address_book_test