name: unit testing

on:
  push:
  pull_request:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo
        uses: actions/checkout@v4  # Check out the repository
        with: 
          submodules: true

      - name: get cmake
        uses: lukka/get-cmake@v3.29.3

      - name: create folder
        run: mkdir build
            cd ./build

      - name: build cmake
        run: cmake -S . -B build

      - name: build
        run: cmake --build build -j

      - name: Run Unit Tests  # Run unit tests using Maven
        run: ./build/address_book_test